- hosts: localhost
  tasks:
  - name: Cilium policy disable all traffic
    community.kubernetes.k8s:
      state: present
      kubeconfig: /sched/kubeconfig.yaml
      definition:
        apiVersion: cilium.io/v2
        kind: CiliumNetworkPolicy
        metadata:
          name: disable-all-traffic-for-hello-labels
          namespace: cilium-test
        spec:
          endpointSelector:
            matchLabels:
              app: hello
          ingress:
            - {}
          egress:
            - {}